services:
  api:
    build:
      context: .
      dockerfile: ChatBoard.API\Dockerfile
      target: prod
    ports:
      - "8080:8080"
    env_file:
        - ChatBoard.API/.env
    depends_on:
        - postgres
    profiles:
        - app

  migration:
    build:
        context: .
        dockerfile: ChatBoard.API\Dockerfile
        target: migrator
    env_file:
        - ChatBoard.API/.env
    environment:
        - MIGRATION_MODE=true        
    depends_on:
        - postgres
    profiles:
        - migration

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_Password}
      POSTGRES_USER: ${DB_Username}
      POSTGRES_DB: ${DB_Database}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
