services:
  api:
    build:
      context: .
      dockerfile: ChatBoard.API\Dockerfile
    ports:
      - "8080:8080"
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
        - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_Password}
      POSTGRES_USER: ${DB_Username}
      POSTGRES_DB: ${DB_Database}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
