services:
  api:
    env_file:
        - ChatBoard.API/.env.staging

  migration:
    env_file:
        - ChatBoard.API/.env.staging

  postgres:
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

volumes:
  postgres_data_staging:
